tests:
	$(CC) -Wall example1.c ../minisdl_audio.c -lm -ldl -lpthread -o example1
	$(CC) -Wall example2.c ../minisdl_audio.c -lm -ldl -lpthread -o example2
	$(CC) -Wall example4.c -lasound -lm -o example4

